Draft: Add floating-point optimizer based on Icing
CakeML/cakeml pull request #865
Opened 2022-03-10 08:38 UTC by HeikoBecker

**Please do not merge yet**, the code depends on the [FloVer](https://gitlab.mpi-sws.org/AVA/FloVer) static analyzer that needs to be integrated with the HOL4 repository or CakeML first

2022-03-10 08:52 UTC, HeikoBecker commented on .gitignore
> +<<<<<<< HEAD
Remove this.

2022-03-10 08:54 UTC, HeikoBecker commented on semantics/Holmakefile
> +
Remove this line.

2022-03-10 08:55 UTC, HeikoBecker commented on semantics/astScript.sml
> +  (* | FP_pred of fp_pred *)
Remove this.

2022-03-10 08:56 UTC, HeikoBecker commented on semantics/astScript.sml
> +  (* | FP_pred _ -> true *)
Remove this.

2022-03-10 08:56 UTC, HeikoBecker commented on semantics/astScript.sml
> +val _ = Define `
Use Definition syntax here, remove type comment.s

2022-03-10 08:58 UTC, HeikoBecker commented on semantics/fpValTreeScript.sml
> +     (* | Fp_pred of fp_pred * fp_word_val *)
Remove this.

2022-03-10 08:59 UTC, HeikoBecker commented on semantics/fpOptScript.sml
> +     (* | Pred  fp_pred * fp_pat *)
Remove.

2022-03-10 09:02 UTC, HeikoBecker commented on semantics/semanticPrimitivesScript.sml
> +   ; assertions : num -> v store -> v sem_env -> bool
Remove this.

2022-03-10 09:03 UTC, HeikoBecker commented on semantics/semanticPrimitivesScript.sml
> +(*val enc_real_uop : real_uop -> v*)
Remove the encoding part here.

2022-04-06 08:28 UTC, HeikoBecker commented
All of the big conceptual issues should be fixed now. This should be good to go as soon as the regression tests pass.

2022-05-06 08:11 UTC, oskarabrahamsson requested changes
Not a fan of custom special-use tactics, esp. in this case when they’re so short.

2022-05-06 09:44 UTC, oskarabrahamsson commented on compiler/repl/evaluate_initScript.sml
> +val icing_rename_tac =
Not a fan of custom special-use tactics, esp. in this case when they’re so short.

2022-05-06 11:15 UTC, oskarabrahamsson approved these changes

2022-05-24 14:01 UTC, merged