Pancake misc lemmas
CakeML/cakeml pull request #923
Opened 2023-01-23 22:56 UTC by mktnk3

Lemmas for Pancake compiler semantics correctness.

2023-01-27 07:53 UTC, myreen requested changes
There all too many uses of `TRY` here. One should strive to avoid use of `TRY` (and `CASE_TAC`).

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  rpt (FULL_CASE_TAC>>gs[])>>TRY (rveq>>gs[])>>
Avoid TRY. Why not just `gvs []` instead of `TRY (rveq>>gs[])`?

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  pairarg_tac>>gs[]>>
Indentation is off here. Click tab in Emacs and this'll be fixed.

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (CASE_TAC>>gs[])>>
avoid TRY and attempt to avoid CASE_TAC, use AllCaseEqs() instead wherever possible

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  rpt (FULL_CASE_TAC>>gs[])>>
one should strive to avoid CASE_TAC (in all its forms)

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_removeProofScript.sml
> +  TRY (rpt (pairarg_tac>>fs[]))
Why `TRY` and `rpt`? Remove the outer TRY

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (rpt (CASE_TAC>>gs[wordPropsTheory.no_install_def]))>>
TRY rpt again... delete the outer TRY

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (last_x_assum (qspecl_then [‘params’, ‘name’] assume_tac)>>
please use >~ or >>~ to find the goal(s) instead of using TRY

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (rpt (CASE_TAC>>gs[wordPropsTheory.no_alloc_def]))>>
same as above

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (last_x_assum (qspecl_then [‘params’, ‘name’] assume_tac)>>
same as above

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (last_x_assum (qspecl_then [‘params’, ‘name’] assume_tac)>>
same as above

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (rpt (CASE_TAC>>gs[wordPropsTheory.no_mt_def]))>>
same as above

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (last_x_assum (qspecl_then [‘params’, ‘name’] assume_tac)>>
same as above

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (CASE_TAC>>gs[])>>
same as above

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (CASE_TAC>>gs[])>>
same as above

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  gs[]>>TRY (rpt (CASE_TAC>>gs[]))>>
same as above

2023-01-27 07:53 UTC, myreen commented on pancake/proofs/loop_to_wordProofScript.sml
> +  TRY (rpt (pairarg_tac>>gs[]))>>
same as above

2023-02-07 23:03 UTC, mktnk3 commented
This can be merged if Magnus is happy with the updates.

2023-02-08 11:50 UTC, merged